# Generated by Django 5.0.1 on 2024-01-06 17:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('profile', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=40)),
                ('phone', models.IntegerField(blank=True, help_text='Contact phone number')),
                ('image', models.ImageField(upload_to='about/')),
                ('aboutme', models.TextField(max_length=20000)),
            ],
        ),
        migrations.CreateModel(
            name='Cattigory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('job', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='home/')),
            ],
        ),
        migrations.CreateModel(
            name='Portfoilo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='protfolio/')),
                ('text', models.CharField(max_length=50)),
                ('job', models.CharField(max_length=50)),
                ('date', models.DateField(blank=True, default=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('icon1', models.CharField(max_length=20)),
                ('icon2', models.CharField(max_length=20)),
                ('job', models.CharField(max_length=50)),
                ('subtitle', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=15)),
                ('percentage', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='blog/')),
                ('text', models.CharField(max_length=100)),
                ('subtitle', models.CharField(max_length=500)),
                ('auth_image', models.ImageField(upload_to='auth/')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_author', to=settings.AUTH_USER_MODEL)),
                ('cattigory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_cattigory', to='home.cattigory')),
            ],
        ),
    ]
